language: python
python:
  - "3.7.3"

stages:
  - name: test
  - name: deploy

jobs:
  include:
    - stage: test
      name: Unit Tests
      script: python manage.py test
    - stage: deploy
      name: Heroku Deploy
      script: /bin/true
      deploy:
        provider: heroku
        api_key:
          secure:  MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3QZQGHmY+Q5uKOhjoEki D6SRDQZiCmcOl0jI0KbRsDF2PVb2uUJ9IwlsD5Q7xUfHxel+y8tjwDQ+z9QVdDEa g5O+aF2TCqCpB9BFWMsHJUGfoZez0p6Mt02l2vpr7DDvEN/g8PaSXTihiJu8ggI+ FNmi5k+7jqUMXdpXCd0vvNcxFiXK6ryqqmly8rkHtaS3khROml32xXCzw3D1CeHu 7cYroRMgZTjHKBs5RQZKIgKOwfMdGO3SijXjdhMAlnTRz1b0UEq6MlZP4Ym3UlXc AZ4nvUvNo1/v1XOnevJrrALkOpbsg/8TVw+vHWpISqxzVhdJcdw/bGM1VpAaEIgf zAOFBWTnt14YniZTHtIzGyq4fgfTt3gkgrJsu71UDH/CATSraeKmtwIivMjwnlYh phvWCa5zXF27UYFo2VPvrMfaLZV5gbaH7NuQ3IuX4bUXmgUg1ewAQSlMEACnuAKw x0rXUjKP1/yj4zlp4tfSCBPGIS/rCaV2ZyxwMQpoJnXsnxD8BXWALGp9tIKRlzxk O6HrR9Lb5q1ZJGpxlhdIvxLWXFv12JrXHoveuVVTOF1NSHofPjiOuj9AuMgvX5Fn EH9GkwnNRia0Q2rnggbBnxamLm2SF9iqBQdZRMf1qjJf9RXT1pSoOomrfBySfpas Xyxm1vCa5dcQtMx8hhsSbA8CAwEAAQ=
        app: emr-acelera-ecomm
        on: master
        run: "python manage.py migrate"
